spring:
  application:
     name: candidate-intake-generation-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  contextPath: /intake-generation-service
  port: 8100