spring.jpa.hibernate.ddl_auto: none
spring.jpa.hibernate.naming_strategy: org.hibernate.cfg.EJB3NamingStrategy

intakeServiceNotificationUrl: http://localhost:8100/intake-generation-service/notify

server:
        contextPath: /candidate-service
        port: 8090